### ISSUE TITLE
Review Zvenyach's blog posts

### ISSUE THREAD

**Issue by lukefretwell** [cagov/codeCAgov#24]
https://medium.com/@vdavez/the-trouble-with-the-federal-source-code-policy-and-what-to-do-about-it-part-one-f1f26d0232ab

**Comment by abquirarte** [comment]
Here are the drafts of the series:

https://medium.com/@vdavez/the-trouble-with-the-federal-source-code-policy-and-what-to-do-about-it-part-one-f1f26d0232ab

https://medium.com/@vdavez/the-trouble-with-the-federal-source-code-policy-and-what-to-do-about-it-part-two-db417970165b

https://medium.com/@vdavez/the-trouble-with-the-federal-source-code-policy-and-what-to-do-about-it-part-three-17a7fb1d1cab

https://medium.com/@vdavez/the-trouble-with-the-federal-source-code-policy-and-what-to-do-about-it-part-four-84fa149d86f (edited)

**Comment by lukefretwell** [comment]
Takeaways:

* Tech neutrality language gave the policy less teeth. Should have been applied to existing, but not new, custom-built software.
* 20% pilot program wasn't effective, and no one wanted it

Key quote:

> After the 20% pilot program sunsets in August 2019, the government should change its policy to (1) adopt a narrower definition of custom-developed code and expressly exclude commercial items (and minor modifications to commercial items) from the policy; (2) for custom-developed code, abandon technology neutrality and explicitly implement an Open Source by Default mandate; and (3) require dual licensing of custom-developed code: open-source licensing in addition to unlimited right.
