### ISSUE TITLE
Provide documented guidelines and best practices to help define the “why” for using and sharing Open Source beyond the policy language.

### ISSUE THREAD

**Issue by lukefretwell** [cagov/codeCAgov#25]
Reference: https://docs.google.com/document/d/1hXYzV_KW49epVuj9EuUGP1hNNARRMf_yVi1Uz5XX_oI/edit#heading=h.5hcigc7ckh0m

**Comment by lukefretwell** [comment]
@abquirarte ready for your 👀 !

**Comment by davisopendataguy** [comment]
WIFIM: thanks, Luke!
