### ISSUE TITLE
Create guiding principles.

### ISSUE THREAD

**Issue by lukefretwell** [cagov/codecagov#32]
See 'About' section (Objective / Mission / Values )(https://docs.google.com/document/d/1hXYzV_KW49epVuj9EuUGP1hNNARRMf_yVi1Uz5XX_oI/edit#heading=h.rlkpz1qmsr5v)

**Comment by lukefretwell** [comment]
@marctjones @abquirarte comments?

**Comment by abquirarte** [comment]
adding comments right now/today.

**Comment by davisopendataguy** [comment]
We raised the point about this implementation being done in the open in yesterday's staff meeting.  People appreciative and intrigued.

**Comment by lukefretwell** [comment]
@abquirarte ready for your 👀!

**Comment by lukefretwell** [comment]
Align with CDT slides.

![screen shot 2018-10-11 at 2 08 34 pm 2](https://user-images.githubusercontent.com/1569463/47665428-54263900-db5e-11e8-9898-a3cf2f7f4e6e.png)
![screen shot 2018-10-11 at 2 11 35 pm 2](https://user-images.githubusercontent.com/1569463/47665429-54263900-db5e-11e8-82f0-31d2d7d6c45e.png)
![screen shot 2018-10-11 at 2 21 57 pm 2](https://user-images.githubusercontent.com/1569463/47665430-54becf80-db5e-11e8-8e8c-c7e699214b4c.png)

cc @BettyJablonsky @StateOfCalifornia

**Comment by abquirarte** [comment]
@lukefretwell I might just make some edits and incorporate the principles I mentioned 6 days ago :) I think we should try to be consistent.
