### ISSUE TITLE
Send message to DWSN participants to recruit Code Coordinators

### ISSUE THREAD

**Issue by lukefretwell** [cagov/codecagov#58]
@abquirarte let's coordinate on messaging.

**Comment by abquirarte** [comment]
Let's do it!

Angélica Quirarte, “Angie”
Assistant Secretary for Digital Engagement
California Government Operations Agency
Direct: 916-651-9035 | Cell: 916-812-6864

"Our leaders develop and inspire our workforce to deliver great results for Californians."
________________________________

**Comment by abquirarte** [comment]
Sent 11/26 inviting them to attend the townhalls prior to soft-launch. - We should do this again for the next DWSN meeting.
