### ISSUE TITLE
Review resource assessment for code.ca.gov

### ISSUE THREAD

**Issue by lukefretwell** [cagov/codecagov#71]
cc @BettyJablonsky @abquirarte 

https://docs.google.com/document/d/1r9ZkuqorDj1hYOrE3Pb6VVZTzfGnGWLyju4NFMvA3Y8/edit?usp=sharing

**Comment by abquirarte** [comment]
Closing on the assumption that this was done by CDT to help inform their efforts to fork code.ca.gov
